services:
  - type: web
    name: chemical-equipment-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chemical_equipment.wsgi:application
    workingDir: backend
